### ISSUE TITLE
Поведение курсора в хедере 

### ISSUE THREAD

**Issue by AndrewSherstyuk** [AndrewSherstyuk/PencilBOOM#2]
Правильное поведение курсора наблюдается только на кнопке Выставки в хедере: как только курсор попадает на фиолетовое поле кнопки, курсор превращается в руку, а сама кнопка переходит в ховер-состояние. Отличия остальных элементов в следующем:
1. Кнопка К Призам: курсор превращается в руку только при наведении на надпись К Призам и несколько пикселей вокруг нее.
2. Кнопка меню: в ховер-состояние кнопка переходит только при наведении курсора на саму кнопку, то есть перехода в ховер нет при попадании курсора на красную поверхность кнопки. В руку курсор не превращается на этой кнопке вообще. 
3. Курсор должен превращаться в руку при наведении его на кнопки языков в языковом селекторе. Сами кнопки должны быть кликабильными и при выборе становиться красными. Не выбранный язык должен становиться белым. Темный фиолетовый фон не должен меняться при ховере.
4. Название также должно быть кликабильным: клик по нему должен вести на главную страницу Гениариум. Курсор должен становиться рукой немедленно по факту попадания на белый фон кнопки.

**Comment by alunenko** [comment]
resolved
