### ISSUE TITLE
Контент и рыбы перекрывают меню

### ISSUE THREAD

**Issue by AndrewSherstyuk** [AndrewSherstyuk/PencilBOOM#3]
http://rm.d.pr/yeQt
1. Меню в открытом состоянии должно перекрывать контент.
2. Рыбы же пусть плавают сверху меню для придания вящего психоделического эффекта происходящему.

**Comment by alunenko** [comment]
Верно, меню будет перекрывать контент, рыбок можно оставить и как сейчас )
Такие "баги" получаются из-за накатывания новой версии в старую. Поддержка старой версии делается для того, что бы можно было:
- обновлять сервер;
- видеть апдейты целиком в странице.
  Скоро будет готова основная версия, которая сольется в мастер и больше таких ситуаций не будет.

**Comment by AndrewSherstyuk** [comment]
Так а рыбы смогут плавать поверх меню? Реально прикольная фишка - удачный импровиз.

**Comment by alunenko** [comment]
Конечно!
